server:
  port: 8050
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          order_inserts: true
        default_schema: PUBLIC
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false

app:
  endpoints:
    tickers: https://www.sec.gov/files/company_tickers.json
